### ISSUE TITLE
Example breakpoints yml label needs to be a string

### ISSUE THREAD

**Issue by zhawkins** [mediacurrent/theme_generator_8#17]
```
foo.srcset.16_9:
  label: 16:9
  mediaQuery: ''
  weight: 0
  multipliers:
    - 1x
```
Needs to be updated to be:
```
foo.srcset.16_9:
  label: '16:9'
  mediaQuery: ''
  weight: 0
  multipliers:
    - 1x
```
