### ISSUE TITLE
Twig namespaces is the wrong format in theme.info.yml for Components module 3.x

### ISSUE THREAD

**Issue by brotkel** [mediacurrent/theme_generator_8#96]
When a theme is generated, it tries to configure the components  namespace with this format:
```
component-libraries:
  finenothings:
    paths:
      - src/patterns/global
      - src/patterns/components
      - src/patterns/pages
      - src/templates
```
This results in the theme immediately causing a PHP error where it can't find the components that are referenced in the custom templates. 
The page for components shows that components should be included in this structure:
```
components:
 namespaces:
    myLib:
      - myLibFiles
 ```
Looks like this structure was marked as [deprecated in 2.x and has been removed in 3.x](https://www.drupal.org/docs/contributed-modules/components/registering-twig-namespaces#s-old-api-in-8x-1x). I would recommend updating the generator and making 2.x the minimum version, as it supports Drupal 9.
